#!/bin/bash
# specify the queue name
#PBS -q gstar
# resource requests
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:01:00:00
#PBS -N SAGE_1024 
#PBS -l pmem=8gb

# list the assigned CPUs and GPUs
echo Deploying job to CPUs ...
cat $PBS_NODEFILE
#echo and using GPU ...
#cat $PBS_GPUFILE

module load gsl/x86_64/gnu/1.9


/home/jseiler/SAGE-stuff/post_processed_SAGE/sage /home/jseiler/SAGE-stuff/input/mysim_1024.par > /lustre/projects/p004_swin/jseiler/anne_output_january/SAGE_1024.dat
